Feature/all cities
Craig180885-napier/Group-Project pull request #53
Opened 2021-02-28 18:07 UTC by Craig180885-napier

Use case 3.1 for review.  Wasn't so easy to figure out how to filter continent etc

2021-02-28 19:05 UTC, scan-lan requested changes, later dismissed
just a few small comments

2021-02-28 19:05 UTC, scan-lan commented on src/main/java/com/napier/sem/City.java
> + * we show when displaying a country.
We'll need to update this comment

2021-02-28 19:05 UTC, scan-lan commented on src/main/java/com/napier/sem/City.java
> +    private String code;
City won't have a Code field

2021-02-28 19:05 UTC, scan-lan commented on src/main/java/com/napier/sem/City.java
> +        code = result.getString("code");
Same again

2021-02-28 19:05 UTC, scan-lan commented on src/main/java/com/napier/sem/DAO.java
> +// Constants that can be used as parameters when calling overloaded methods
I think this is an artefact from something that didn't go in

2021-02-28 19:05 UTC, scan-lan commented on src/main/java/com/napier/sem/DAO.java
> +     * @return An ArrayList of country objects
We need to update this comment

2021-03-01 10:09 UTC, Craig180885-napier commented
Cool I'll make these changes.  @LukasP23 and/or @M7DLX  can approve

2021-03-01 12:34 UTC, Craig180885-napier commented on src/main/java/com/napier/sem/City.java
> +    private String code;
Yeah that was me trying something out for 3.2 etc, I'll get rid

2021-03-02 12:58 UTC, LukasP23 approved these changes
Sick

2021-03-02 12:59 UTC, merged